//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raidfelden.Discord.Bot.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class i18n {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal i18n() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Raidfelden.Discord.Bot.Resources.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Base_Messages_Reply_Failure {
            get {
                return ResourceManager.GetString("Base_Messages_Reply_Failure", resourceCulture);
            }
        }
        
        public static string Base_Messages_Reply_Interactive {
            get {
                return ResourceManager.GetString("Base_Messages_Reply_Interactive", resourceCulture);
            }
        }
        
        public static string Base_Messages_Reply_Success {
            get {
                return ResourceManager.GetString("Base_Messages_Reply_Success", resourceCulture);
            }
        }
        
        public static string BotName {
            get {
                return ResourceManager.GetString("BotName", resourceCulture);
            }
        }
        
        public static string BotPrefix {
            get {
                return ResourceManager.GetString("BotPrefix", resourceCulture);
            }
        }
        
        public static string Gyms_Errors_InteractiveMode {
            get {
                return ResourceManager.GetString("Gyms_Errors_InteractiveMode", resourceCulture);
            }
        }
        
        public static string Gyms_Errors_NothingFound {
            get {
                return ResourceManager.GetString("Gyms_Errors_NothingFound", resourceCulture);
            }
        }
        
        public static string Gyms_Errors_ToManyFound {
            get {
                return ResourceManager.GetString("Gyms_Errors_ToManyFound", resourceCulture);
            }
        }
        
        public static string ModuleRaidsCommandAdd {
            get {
                return ResourceManager.GetString("ModuleRaidsCommandAdd", resourceCulture);
            }
        }
        
        public static string ModuleRaidsCommandAddDescription {
            get {
                return ResourceManager.GetString("ModuleRaidsCommandAddDescription", resourceCulture);
            }
        }
        
        public static string ModuleRaidsIdentifier {
            get {
                return ResourceManager.GetString("ModuleRaidsIdentifier", resourceCulture);
            }
        }
        
        public static string Pokemon_Errors_InteractiveMode {
            get {
                return ResourceManager.GetString("Pokemon_Errors_InteractiveMode", resourceCulture);
            }
        }
        
        public static string Pokemon_Errors_NothingFound {
            get {
                return ResourceManager.GetString("Pokemon_Errors_NothingFound", resourceCulture);
            }
        }
        
        public static string Pokemon_Errors_ToManyFound {
            get {
                return ResourceManager.GetString("Pokemon_Errors_ToManyFound", resourceCulture);
            }
        }
        
        public static string Raids_Errors_Hatch_NoEntryFound {
            get {
                return ResourceManager.GetString("Raids_Errors_Hatch_NoEntryFound", resourceCulture);
            }
        }
        
        public static string Raids_Errors_LevelToHigh {
            get {
                return ResourceManager.GetString("Raids_Errors_LevelToHigh", resourceCulture);
            }
        }
        
        public static string Raids_Errors_LevelToLow {
            get {
                return ResourceManager.GetString("Raids_Errors_LevelToLow", resourceCulture);
            }
        }
        
        public static string Raids_Errors_NotAnRaidImage {
            get {
                return ResourceManager.GetString("Raids_Errors_NotAnRaidImage", resourceCulture);
            }
        }
        
        public static string Raids_Errors_TimeFormat {
            get {
                return ResourceManager.GetString("Raids_Errors_TimeFormat", resourceCulture);
            }
        }
        
        public static string Raids_Errors_Unexpected {
            get {
                return ResourceManager.GetString("Raids_Errors_Unexpected", resourceCulture);
            }
        }
        
        public static string Raids_Messages_BossAdded {
            get {
                return ResourceManager.GetString("Raids_Messages_BossAdded", resourceCulture);
            }
        }
        
        public static string Raids_Messages_BossHatched {
            get {
                return ResourceManager.GetString("Raids_Messages_BossHatched", resourceCulture);
            }
        }
        
        public static string Raids_Messages_EggAdded {
            get {
                return ResourceManager.GetString("Raids_Messages_EggAdded", resourceCulture);
            }
        }
        
        public static string Raids_Messages_Ocr_Successful_Title {
            get {
                return ResourceManager.GetString("Raids_Messages_Ocr_Successful_Title", resourceCulture);
            }
        }
        
        public static string Raids_Messages_Successful_Text {
            get {
                return ResourceManager.GetString("Raids_Messages_Successful_Text", resourceCulture);
            }
        }
        
        public static string Raids_Messages_Successful_Title {
            get {
                return ResourceManager.GetString("Raids_Messages_Successful_Title", resourceCulture);
            }
        }
    }
}
